version: "3.1"

services:
  api:
    build: "./api"
    ports:
      - "3002:3002"
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27018
    command: --bind_ip_all --port 27018
